### ISSUE TITLE
LabelNotFoundException during CALL

### ISSUE THREAD

**Issue by Justist** [timvandermeij/whitespace-interpreter#8]
A LabelNotFoundException pops up when trying to interpret helloworld.ws, as the first MARK is done after 2 CALLs, and thus the map 'labels' is empty during the execution of these CALLs. No wonder the label, which it tries to find(), isn't found!

Try testing it for other programs, or find information about CALLs without MARKs on beforehand.

**Comment by willem-o** [comment]
This is not a bug in our program, but a bug in hello_world.ws. We could add a procedure that performs semantics analysis on a Program such that we can reject these wrong programs.
